-- Betynz v6.2.0 core football database
-- Run this migration in the Supabase SQL editor before starting the API.

create extension if not exists pgcrypto;

create or replace function public.betynz_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.leagues (
  id bigint generated by default as identity primary key,
  external_league_id bigint not null,
  name text not null,
  country text,
  season integer not null,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leagues_external_season_key unique (external_league_id, season)
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  external_team_id bigint not null unique,
  name text not null,
  country text,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fixtures (
  id bigint generated by default as identity primary key,
  external_fixture_id bigint not null unique,
  league_id bigint not null references public.leagues(id) on delete restrict,
  season integer not null,
  fixture_date timestamptz not null,
  home_team_id bigint not null references public.teams(id) on delete restrict,
  away_team_id bigint not null references public.teams(id) on delete restrict,
  halftime_home integer,
  halftime_away integer,
  fulltime_home integer,
  fulltime_away integer,
  status text not null default 'NS',
  venue text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fixtures_different_teams check (home_team_id <> away_team_id)
);

create table if not exists public.team_htft_profiles (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  season integer not null,
  scope text not null check (scope in ('overall', 'home', 'away', 'recent6')),
  matches_played numeric not null default 0,
  ww numeric not null default 0,
  wd numeric not null default 0,
  wl numeric not null default 0,
  dw numeric not null default 0,
  dd numeric not null default 0,
  dl numeric not null default 0,
  lw numeric not null default 0,
  ld numeric not null default 0,
  ll numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_htft_profiles_scope_key unique (team_id, league_id, season, scope)
);

create table if not exists public.team_goal_profiles (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  league_id bigint not null references public.leagues(id) on delete cascade,
  season integer not null,
  scope text not null check (scope in ('overall', 'home', 'away', 'recent6')),
  matches_played numeric not null default 0,
  goals_scored numeric not null default 0,
  goals_conceded numeric not null default 0,
  scoring_rate double precision not null default 0,
  conceding_rate double precision not null default 0,
  failed_to_score_rate double precision not null default 0,
  clean_sheet_rate double precision not null default 0,
  btts_rate double precision not null default 0,
  over_15_rate double precision not null default 0,
  over_25_rate double precision not null default 0,
  under_35_rate double precision not null default 0,
  scored_2plus_rate double precision not null default 0,
  conceded_2plus_rate double precision not null default 0,
  first_half_scoring_rate double precision not null default 0,
  second_half_scoring_rate double precision not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_goal_profiles_scope_key unique (team_id, league_id, season, scope)
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  engine_version text not null,
  primary_market text not null,
  primary_selection text not null,
  probability double precision,
  confidence double precision not null default 0,
  confidence_tier text,
  strongest_transition text,
  transition_probability double precision,
  home_goal_support double precision,
  away_goal_support double precision,
  gg_score double precision,
  over_15_score double precision,
  over_25_score double precision,
  under_35_score double precision,
  market_scores jsonb not null default '{}'::jsonb,
  transition_matrix jsonb not null default '{}'::jsonb,
  reasons text[] not null default '{}'::text[],
  warnings text[] not null default '{}'::text[],
  rejected_markets jsonb not null default '[]'::jsonb,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint predictions_fixture_engine_key unique (fixture_id, engine_version)
);

create table if not exists public.prediction_results (
  id bigint generated by default as identity primary key,
  prediction_id bigint not null unique references public.predictions(id) on delete cascade,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  halftime_score text,
  fulltime_score text,
  confirmed_htft text,
  outcome text not null check (outcome in ('WIN', 'LOSS', 'VOID', 'UNABLE_TO_GRADE')),
  profit_loss numeric not null default 0,
  graded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fixtures_fixture_date_idx on public.fixtures (fixture_date);
create index if not exists fixtures_status_date_idx on public.fixtures (status, fixture_date);
create index if not exists fixtures_league_season_idx on public.fixtures (league_id, season, fixture_date);
create index if not exists fixtures_home_team_idx on public.fixtures (home_team_id, fixture_date);
create index if not exists fixtures_away_team_idx on public.fixtures (away_team_id, fixture_date);
create index if not exists team_htft_team_idx on public.team_htft_profiles (team_id, season desc, scope);
create index if not exists team_goal_team_idx on public.team_goal_profiles (team_id, season desc, scope);
create index if not exists predictions_public_idx on public.predictions (published, engine_version, confidence desc);
create index if not exists predictions_fixture_idx on public.predictions (fixture_id);
create index if not exists prediction_results_graded_idx on public.prediction_results (graded_at desc);

-- Keep timestamps accurate even when a caller omits updated_at.
drop trigger if exists leagues_set_updated_at on public.leagues;
create trigger leagues_set_updated_at before update on public.leagues
for each row execute function public.betynz_set_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at before update on public.teams
for each row execute function public.betynz_set_updated_at();

drop trigger if exists fixtures_set_updated_at on public.fixtures;
create trigger fixtures_set_updated_at before update on public.fixtures
for each row execute function public.betynz_set_updated_at();

drop trigger if exists team_htft_profiles_set_updated_at on public.team_htft_profiles;
create trigger team_htft_profiles_set_updated_at before update on public.team_htft_profiles
for each row execute function public.betynz_set_updated_at();

drop trigger if exists team_goal_profiles_set_updated_at on public.team_goal_profiles;
create trigger team_goal_profiles_set_updated_at before update on public.team_goal_profiles
for each row execute function public.betynz_set_updated_at();

drop trigger if exists predictions_set_updated_at on public.predictions;
create trigger predictions_set_updated_at before update on public.predictions
for each row execute function public.betynz_set_updated_at();

drop trigger if exists prediction_results_set_updated_at on public.prediction_results;
create trigger prediction_results_set_updated_at before update on public.prediction_results
for each row execute function public.betynz_set_updated_at();

-- The browser never connects to these tables directly. The Render API uses the
-- Supabase service-role key and returns only the public dashboard shape.
alter table public.leagues enable row level security;
alter table public.teams enable row level security;
alter table public.fixtures enable row level security;
alter table public.team_htft_profiles enable row level security;
alter table public.team_goal_profiles enable row level security;
alter table public.predictions enable row level security;
alter table public.prediction_results enable row level security;

revoke all on table public.leagues from anon, authenticated;
revoke all on table public.teams from anon, authenticated;
revoke all on table public.fixtures from anon, authenticated;
revoke all on table public.team_htft_profiles from anon, authenticated;
revoke all on table public.team_goal_profiles from anon, authenticated;
revoke all on table public.predictions from anon, authenticated;
revoke all on table public.prediction_results from anon, authenticated;
